-- CreateTable
CREATE TABLE `admin` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `namaAdmin` VARCHAR(191) NOT NULL DEFAULT '',
    `email` VARCHAR(191) NOT NULL DEFAULT '',
    `password` VARCHAR(191) NOT NULL DEFAULT '',
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `car` (
    `carID` INTEGER NOT NULL AUTO_INCREMENT,
    `Nopol` INTEGER NOT NULL DEFAULT 0,
    `carType` VARCHAR(191) NOT NULL DEFAULT '',
    `Price` INTEGER NOT NULL DEFAULT 0,

    PRIMARY KEY (`carID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `rent` (
    `rentID` INTEGER NOT NULL AUTO_INCREMENT,
    `carID` INTEGER NOT NULL DEFAULT 0,
    `namaPenyewa` VARCHAR(191) NOT NULL DEFAULT '',
    `bookData` INTEGER NOT NULL DEFAULT 0,
    `lamaSewa` VARCHAR(191) NOT NULL DEFAULT '',
    `totalBayar` INTEGER NOT NULL DEFAULT 0,

    PRIMARY KEY (`rentID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `rent` ADD CONSTRAINT `rent_carID_fkey` FOREIGN KEY (`carID`) REFERENCES `car`(`carID`) ON DELETE RESTRICT ON UPDATE CASCADE;
